In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('energydata_complete.csv')

In [3]:
df

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [4]:
df = df.drop('date', axis=1)
df = df.drop('lights', axis=1)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalized_df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)
normalized_df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,19725,19726,19727,19728,19729,19730,19731,19732,19733,19734
Appliances,0.046729,0.046729,0.037383,0.037383,0.046729,0.037383,0.046729,0.046729,0.046729,0.056075,...,0.196262,0.158879,0.102804,0.093458,0.074766,0.084112,0.074766,0.242991,0.383178,0.392523
T1,0.327350,0.327350,0.327350,0.327350,0.327350,0.327350,0.327350,0.323830,0.316790,0.323830,...,0.912003,0.919747,0.919747,0.930306,0.923266,0.926786,0.919747,0.919747,0.919747,0.919747
RH_1,0.566187,0.541326,0.530502,0.524080,0.531419,0.522980,0.515824,0.510137,0.511169,0.524723,...,0.523897,0.536831,0.562334,0.555087,0.545913,0.537657,0.536006,0.538666,0.549491,0.538758
T2,0.225345,0.225345,0.225345,0.225345,0.225345,0.225345,0.225345,0.225345,0.225345,0.227526,...,0.719651,0.719651,0.719651,0.717366,0.718052,0.711655,0.701769,0.692651,0.677054,0.666171
RH_2,0.684038,0.682140,0.679445,0.678414,0.676727,0.675883,0.675883,0.675883,0.674009,0.673072,...,0.597151,0.597874,0.614584,0.620449,0.620602,0.606309,0.607836,0.627198,0.634717,0.632902
T3,0.215188,0.215188,0.215188,0.215188,0.215188,0.215188,0.215188,0.210203,0.210203,0.215188,...,0.897308,0.885399,0.869336,0.846627,0.841088,0.830841,0.825302,0.818378,0.805085,0.799546
RH_3,0.746066,0.748871,0.755569,0.758685,0.758685,0.755569,0.754012,0.754012,0.748871,0.752298,...,0.560523,0.548372,0.557408,0.573142,0.575946,0.579374,0.582178,0.603988,0.585294,0.579062
T4,0.351351,0.351351,0.344745,0.341441,0.341441,0.341441,0.341441,0.341441,0.341441,0.341441,...,0.864865,0.864865,0.864865,0.864865,0.864865,0.864865,0.864865,0.864865,0.864865,0.864865
RH_4,0.764262,0.782437,0.778062,0.770949,0.762697,0.771233,0.773794,0.776924,0.773794,0.786883,...,0.757149,0.761417,0.763978,0.766823,0.766823,0.765258,0.765258,0.771233,0.773794,0.781192
T5,0.175506,0.175506,0.175506,0.175506,0.178691,0.172320,0.169135,0.169135,0.175506,0.169135,...,0.752031,0.752031,0.752031,0.752031,0.752031,0.752031,0.754897,0.754897,0.752031,0.752031
RH_5,0.381691,0.381691,0.380037,0.380037,0.380037,0.379135,0.378183,0.377180,0.378684,0.378684,...,0.334478,0.333576,0.335480,0.337485,0.338487,0.339590,0.338487,0.337585,0.336583,0.336583
T6,0.381070,0.375443,0.367487,0.363800,0.361859,0.359918,0.358851,0.356717,0.354776,0.356717,...,0.948770,0.941881,0.928492,0.932276,0.922573,0.898317,0.880852,0.864260,0.829525,0.788580
RH_6,0.841827,0.839872,0.830704,0.833401,0.848264,0.857095,0.860364,0.863734,0.871857,0.875902,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
T7,0.170594,0.170594,0.170594,0.164310,0.170594,0.164310,0.164310,0.161169,0.167452,0.170594,...,0.848256,0.858624,0.855662,0.858624,0.858624,0.858624,0.864010,0.862394,0.858624,0.858624
RH_7,0.653428,0.651064,0.646572,0.641489,0.639362,0.640426,0.638298,0.638298,0.645390,0.648936,...,0.750659,0.760071,0.761297,0.763050,0.764691,0.755319,0.752280,0.751773,0.748075,0.739504
T8,0.173329,0.173329,0.173329,0.164175,0.164175,0.164175,0.164175,0.164175,0.164175,0.164175,...,0.736955,0.744034,0.753738,0.759231,0.765334,0.768386,0.768386,0.768386,0.764953,0.771681
RH_8,0.661412,0.660155,0.655586,0.650788,0.650788,0.650788,0.650788,0.650788,0.650788,0.650788,...,0.744802,0.755038,0.750514,0.728695,0.714359,0.701645,0.691912,0.687457,0.682617,0.690062
T9,0.223032,0.226500,0.219563,0.219563,0.219563,0.219563,0.219563,0.219563,0.219563,0.219563,...,0.864724,0.864724,0.864724,0.864724,0.864724,0.864724,0.864724,0.864724,0.864724,0.864724
RH_9,0.677290,0.678532,0.676049,0.671909,0.671909,0.667357,0.667357,0.667357,0.667357,0.667357,...,0.725717,0.723766,0.726462,0.727846,0.727580,0.729443,0.729443,0.729443,0.730581,0.731719
T_out,0.372990,0.369239,0.365488,0.361736,0.357985,0.354234,0.350482,0.351018,0.351554,0.352090,...,0.897106,0.898178,0.899250,0.900322,0.896034,0.891747,0.887460,0.883173,0.878885,0.874598
Press_mm_hg,0.097674,0.100000,0.102326,0.104651,0.106977,0.109302,0.111628,0.113178,0.114729,0.116279,...,0.605814,0.604651,0.603488,0.602326,0.602326,0.602326,0.602326,0.602326,0.602326,0.602326
RH_out,0.894737,0.894737,0.894737,0.894737,0.894737,0.894737,0.894737,0.892544,0.890351,0.888158,...,0.407895,0.407895,0.407895,0.407895,0.412281,0.416667,0.421053,0.425439,0.429825,0.434211
Windspeed,0.500000,0.476190,0.452381,0.428571,0.404762,0.380952,0.357143,0.369048,0.380952,0.392857,...,0.178571,0.190476,0.202381,0.214286,0.226190,0.238095,0.250000,0.261905,0.273810,0.285714
Visibility,0.953846,0.894872,0.835897,0.776923,0.717949,0.658974,0.600000,0.600000,0.600000,0.600000,...,0.330769,0.328205,0.325641,0.323077,0.335897,0.348718,0.361538,0.374359,0.387179,0.400000
Tdewpoint,0.538462,0.533937,0.529412,0.524887,0.520362,0.515837,0.511312,0.510558,0.509804,0.509050,...,0.900452,0.901961,0.903469,0.904977,0.903469,0.901961,0.900452,0.898944,0.897436,0.895928
rv1,0.265449,0.372083,0.572848,0.908261,0.201611,0.898441,0.944735,0.660808,0.629118,0.061691,...,0.460165,0.505917,0.035828,0.364922,0.339276,0.861981,0.985726,0.583979,0.126371,0.682391
rv2,0.265449,0.372083,0.572848,0.908261,0.201611,0.898441,0.944735,0.660808,0.629118,0.061691,...,0.460165,0.505917,0.035828,0.364922,0.339276,0.861981,0.985726,0.583979,0.126371,0.682391

In [6]:
df = normalized_df

In [7]:
x = df[['T2']]

In [8]:
y = df[['T6']]

In [9]:
x

             T2
0      0.225345
1      0.225345
2      0.225345
3      0.225345
4      0.225345
...         ...
19730  0.711655
19731  0.701769
19732  0.692651
19733  0.677054
19734  0.666171

[19735 rows x 1 columns]

In [10]:
y

             T6
0      0.381070
1      0.375443
2      0.367487
3      0.363800
4      0.361859
...         ...
19730  0.898317
19731  0.880852
19732  0.864260
19733  0.829525
19734  0.788580

[19735 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr = LinearRegression()

In [15]:
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
lr.coef_

array([[0.8910771]])

In [17]:
lr.intercept_

array([0.13176428])

In [18]:
y_pred = lr.predict(x_test)

In [19]:
y_test.head(), y_pred[0:5]

(             T6
 8980   0.211427
 2754   0.250182
 9132   0.168777
 14359  0.501383
 8875   0.155193,
 array([[0.23928945],
        [0.46794238],
        [0.23108472],
        [0.63635531],
        [0.1552989 ]]))

In [20]:
from sklearn.metrics import r2_score

In [21]:
r2_score = r2_score(y_test, y_pred)
r2_score

0.6427789637197382

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
mean_squared_error(y_test, y_pred)

0.011166285957258446

In [24]:
from sklearn.metrics import mean_absolute_error

In [25]:
mae = mean_absolute_error(y_test, y_pred)
mae.round(2)

0.08

In [26]:
rss = np.sum(np.square(y_test-y_pred))

In [40]:
rss.round(2)

T6    66.12
dtype: float64

In [28]:
from sklearn.metrics import mean_squared_error

In [29]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [30]:
rmse.round(3)

0.106

In [31]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.4)
ridge.fit(x_train, y_train)
y2_pred = ridge.predict(x_test)

In [32]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.001)
lasso.fit(x_train, y_train)
y3_pred = lasso.predict(x_test)

In [33]:
def get_weights_df(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

In [34]:
linear_model_weights = get_weights_df(lr, x_train, 'Linear_Model_Weight')
ridge_weight_df =  get_weights_df(ridge, x_train, 'Ridge_Weight')
lasso_weight_df= get_weights_df(lasso, x_train, 'Lasso_Weight')

final_weights = pd.merge(linear_model_weights, ridge_weight_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weight_df, on='Features')

Exception: Data must be 1-dimensional

In [35]:
mean_squared_error(y_test, y2_pred)

0.011166294439861444

In [36]:
rmse = np.sqrt(mean_squared_error(y_test, y2_pred))
rmse

0.10567068865045522

In [37]:
mean_squared_error(y_test, y3_pred)

0.011204717386872806

In [39]:
rmse = np.sqrt(mean_squared_error(y_test, y3_pred))
rmse.round(3)

0.106